version: '3.9'

services:

    sdwebui:
      container_name: service_sdwebui
      restart: unless-stopped
      build: ./sd
      ports:
        - "7560:7560"
      stop_signal: SIGINT
      deploy:
        resources:
          reservations:
            devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]
